trigger:
  - main

pool:
  name: 'ubuntu-latest'   # <-- this tells Azure DevOps to use your self-hosted pool

steps:
  - script: node -v
    displayName: 'Show node version'

  - script: npm install
    displayName: 'Install dependencies'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'sc-azure-theju-poc'
      appType: 'webAppLinux'
      appName: 'theju-webapp-poc'
      package: '$(System.DefaultWorkingDirectory)'
